cd /Users/thomasgumbricht/GitHub/kt-gi-test01/Karttur2019GitHub/geoimagine
git submodule add https://github.com/karttur/geoimagine-kartturmain kartturmain
git submodule add https://github.com/karttur/geoimagine-ancillary ancillary
git submodule add https://github.com/karttur/geoimagine-dem dem
git submodule add https://github.com/karttur/geoimagine-endmembers endmembers
git submodule add https://github.com/karttur/geoimagine-export export
git submodule add https://github.com/karttur/geoimagine-extract extract
git submodule add https://github.com/karttur/geoimagine-gdalutilities gdalutilities
git submodule add https://github.com/karttur/geoimagine-gis gis
git submodule add https://github.com/karttur/geoimagine-grace grace
git submodule add https://github.com/karttur/geoimagine-image image
git submodule add https://github.com/karttur/geoimagine-jekyllise jekyllise
git submodule add https://github.com/karttur/geoimagine-ktgraphics ktgraphics
git submodule add https://github.com/karttur/geoimagine-ktnumba ktnumba
git submodule add https://github.com/karttur/geoimagine-ktpandas ktpandas
git submodule add https://github.com/karttur/geoimagine-landsat landsat
git submodule add https://github.com/karttur/geoimagine-layout layout
git submodule add https://github.com/karttur/geoimagine-mask mask
git submodule add https://github.com/karttur/geoimagine-modis modis
git submodule add https://github.com/karttur/geoimagine-overlay overlay
git submodule add https://github.com/karttur/geoimagine-postgresdb postgresdb
git submodule add https://github.com/karttur/geoimagine-projects projects
git submodule add https://github.com/karttur/geoimagine-region region
git submodule add https://github.com/karttur/geoimagine-scalar scalar
git submodule add https://github.com/karttur/geoimagine-sentinel sentinel
git submodule add https://github.com/karttur/geoimagine-setup_db setup_db
git submodule add https://github.com/karttur/geoimagine-setup_process setup_process
git submodule add https://github.com/karttur/geoimagine-smap smap
git submodule add https://github.com/karttur/geoimagine-soilmoisture soilmoisture
git submodule add https://github.com/karttur/geoimagine-specials specials
git submodule add https://github.com/karttur/geoimagine-sqldumps sqldumps
git submodule add https://github.com/karttur/geoimagine-support support
git submodule add https://github.com/karttur/geoimagine-timeseries timeseries
git submodule add https://github.com/karttur/geoimagine-transform transform
git submodule add https://github.com/karttur/geoimagine-updatedb updatedb
git submodule add https://github.com/karttur/geoimagine-userproj userproj
git submodule add https://github.com/karttur/geoimagine-zipper zipper
